dubbo:
  scan:
    base-packages: com.lea     # 扫描 @DubboService 所在包 → 触发服务暴露（关键！不加就不暴露）
  application:
    name: demo-provider
  protocol:
    name: dubbo          # 用 Dubbo2 协议（基于 TCP）
    port: 20881          # 20880 被你另一个 provider(power-bank-ultimate)占了，换 20881
  registry:
#    address: zookeeper://127.0.0.1:2181   # 注册中心
    address: nacos://127.0.0.1:8848   # 注册中心

server:
  port: 9000